# Homework 1
## Mohammad Mehdi Razavi
### Matricola : 2023856
### mohammadmehdirazavi97@gmail.com
At the begining of each chunk of code there is a comment which is the name of problem in hackerrank.

# Problem 1
## Part 1:  Introduction 


In [1]:
# 1.Say "Hello, World!" With Python

print("Hello, World!")

Hello, World!


In [2]:
# 2.Python If-Else

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input().strip())
if(n % 2 == 1):
    print("Weird")
if(n % 2 == 0):
    if(2<= n and n<=5):
        print("Not Weird")
    elif(6 <= n and n <= 20):
        print("Weird")
    elif(20 < n):
        print("Not Weird")

 26


Not Weird


In [3]:
# 3.Arithmetic Operators

if __name__ == '__main__':
    a = int(input())
    b = int(input())
    
    print(a + b)
    print(a - b)
    print(a * b)

1
2
3
-1
2


In [4]:
# 4.Python: Division

if __name__ == '__main__':
    a = int(input())
    b = int(input())
    print(a//b)
    print(a/b)

1
2
0
0.5


In [5]:
# 5.Loops

if __name__ == '__main__':
    n = int(input())
    for i in range(0,n):
        print(i**2)

3
0
1
4


In [7]:
# 6.Write a function

def is_leap(year):
    leap = False
    if(year % 4 == 0):
        if(year % 100 != 0):
            leap = True
        else:
            if(year % 400 == 0):
                leap = True

    return leap

year = int(input())
print(is_leap(year))

2000
True


In [10]:
# 7.Print Function

if __name__ == '__main__':
    n = int(input())
    for i in range(0,n):
        print(i+1, end="")

4
1234

## Part 2 : Data Types

In [6]:
# 1. Lists
if __name__ == '__main__':
    N = int(input())
    data = []
    for i in range(N):
        cmnd = list(input().split())
        
        if cmnd[0] == 'insert':
            data.insert(int(cmnd[1]), int(cmnd[2]))
            
        elif cmnd[0] == 'print':
            print(data)
            
        elif cmnd[0] == 'remove':
            data.remove(int(cmnd[1]))
            
        elif cmnd[0] == 'append':
            data.append(int(cmnd[1]))
                        
        elif cmnd[0] == 'sort':
            data.sort()
                        
        elif cmnd[0] == 'pop':
            data.pop()
                        
        elif cmnd[0] == 'reverse':
            data.reverse()
        


12
insert 0 5
insert 1 10
insert 0 6
print
[6, 5, 10]
remove 6
append 9
append 1
sort
print
[1, 5, 9, 10]
pop
reverse
print
[9, 5, 1]


In [7]:
# 2.List Comprehensions
if __name__ == '__main__':
    x = int(input())
    y = int(input())
    z = int(input())
    n = int(input())
    data = [[i,j,k] for i in range(x+1) for j in range(y+1) for k in range(z+1)]
    ans = [data[i] for i in range(0,len(data)) if sum(data[i]) != n]
    print(ans)

1
1
1
2
[[0, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [1, 1, 1]]


In [8]:
# 3.Find the Runner-Up Score!

if __name__ == '__main__':
    n = int(input())
    arr = list(map(int, input().split()))
    ans = [x for x in arr if x != max(arr)]
    print(max(ans))



5
2 3 6 6 5
5


In [9]:
# 4.Nested Lists
if __name__ == '__main__':
    records_name = []
    records_score = []
    data = [[]]
    for i in range(int(input())):
        name = input()
        score = float(input())
        data.append([name, score])
    data.remove(data[0])
    
    # find the minimum of input data
    minimum = data[0]
    for item in data:
        if(item[1] < minimum[1]):
            minimum = item
            
    #remove the minimum of the input data
    ans = [x for x in data if x[1] != minimum[1]]
    
    # find the minimum score in the second data
    minimum = ans[0]
    for item in ans:
        if(item[1] < minimum[1]):
            minimum = item
    
    #extract the items with minimum score in the second data
    ans = [x for x in ans if x[1] == minimum[1]]
    
    #extract just names
    ans_name = [i[0] for i in ans]
    
    # print sorted names
    for names in sorted(ans_name):
        print(names)
    

5
Harry
37.21
Berry
37.21
Tina
37.2
Akriti
41
Harsh
39
Berry
Harry


In [37]:
# 5.Finding the percentage
if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        student_marks[name] = scores
    query_name = input()
    
    # set 2 decimal point
    format_float = "{:.2f}".format(sum(student_marks[query_name])/len(student_marks[query_name]))

    print(format_float)

2
Harsh 25 26.5 28
Anurag 26 28 30
Harsh
26.50


In [86]:
# 6.Tuples

if __name__ == '__main__':
    n = int(input())
    integer_list = list(map(int, input().split()))
    print(integer_list)
    t = tuple(integer_list)
    print(t)
    print(hash(t))

50
387 38 498 988 434 282 467 641 464 682 341 586 222 736 187 415 330 323 109 818 78 469 560 623 748 782 352 398 196 39 603 344 630 841 794 994 648 293 861 800 944 249 921 10 781 437 915 451 782 262
[387, 38, 498, 988, 434, 282, 467, 641, 464, 682, 341, 586, 222, 736, 187, 415, 330, 323, 109, 818, 78, 469, 560, 623, 748, 782, 352, 398, 196, 39, 603, 344, 630, 841, 794, 994, 648, 293, 861, 800, 944, 249, 921, 10, 781, 437, 915, 451, 782, 262]
(387, 38, 498, 988, 434, 282, 467, 641, 464, 682, 341, 586, 222, 736, 187, 415, 330, 323, 109, 818, 78, 469, 560, 623, 748, 782, 352, 398, 196, 39, 603, 344, 630, 841, 794, 994, 648, 293, 861, 800, 944, 249, 921, 10, 781, 437, 915, 451, 782, 262)
-8100610261461401956


## Part 3 : Strings

In [24]:
# 1. sWAP cASE

def swap_case(s):
    out_str = ""
    for char in s:
        if char.isalpha():
            
            if char.islower():
                char = char.upper()
        
            elif char.isupper():
                char = char.lower()
        
            out_str += char
        
        elif char.isalpha() == False:
            out_str += char
        
    return out_str

if __name__ == '__main__':
    text = input()
    print(swap_case(text))


HackerRank.com presents "Pythonist 2".
hACKERrANK.COM PRESENTS "pYTHONIST 2".


In [ ]:
# 2.String Split and Join

def split_and_join(line):
    # write your code here
    line = line.split(" ")
    line = "-".join(line)
    return line
if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)

In [10]:
# 3.What's Your Name?

def print_full_name(first, last):
    print("Hello " + first + " " + last + "! You just delved into python.")
if __name__ == '__main__':
    first_name = input()
    last_name = input()
    print_full_name(first_name, last_name)

mehdi
razavi
Hello mehdi razavi! You just delved into python.


In [3]:
# 4.Mutations

def mutate_string(string, position, character):
    l = list(string)
    l[position] = character
    string = ''.join(l)
    return string

if __name__ == '__main__':
    s = input()
    i, c = input().split()
    s_new = mutate_string(s, int(i), c)
    print(s_new)

abracadabra
5 k
abrackdabra


In [15]:
# 5.Find a string
def count_substring(string, sub_string):
    count = 0
    for i in range(len(string)):
        if string[i:i+len(sub_string)] == sub_string:
            count += 1
    return count

if __name__ == '__main__':
    string = input().strip()
    sub_string = input().strip()
    
    count = count_substring(string, sub_string)
    print(count)

ABCDCDC
CDC
2


In [18]:
# 6.String Validators

if __name__ == '__main__':
    s = input()
    
    #isalnum
    for char in s:
        first = char.isalnum()
        if(first):
            print(True)
            break
    if(first == False):
        print(False)
    
    #isalpha
    for char in s:
        second = char.isalpha()
        if(second):
            print(True)
            break
    if(second == False):
        print(False)
    
    #isdigit
    for char in s:
        third = char.isdigit()
        if(third):
            print(True)
            break
    if(third == False):
        print(False)
    
    #islower
    for char in s:
        fourth = char.islower()
        if(fourth):
            print(True)
            break
    if(fourth == False):
        print(False)
    
    #isupper
    for char in s:
        fifth = char.isupper()
        if(fifth):
            print(True)
            break
    if(fifth == False):
        print(False)

qA2
True
True
True
True
True


In [19]:
# 7. Text Alignment

#Replace all ______ with rjust, ljust or center. 

thickness = int(input()) #This must be an odd number
c = 'H'

## Top Cone
for i in range(thickness):
    print((c*i).rjust(thickness-1)+c+(c*i).ljust(thickness-1))

# Top Pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))

# Middle Belt
for i in range((thickness+1)//2):
    print((c*thickness*5).center(thickness*6))

# Bottom Pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))

# Bottom Cone
for i in range(thickness):
    print(((c*(thickness-i-1)).rjust(thickness)+c+(c*(thickness-i-1)).ljust(thickness)).rjust(
        thickness*6))

5
    H    
   HHH   
  HHHHH  
 HHHHHHH 
HHHHHHHHH
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
                    HHHHHHHHH 
                     HHHHHHH  
                      HHHHH   
                       HHH    
                        H     


In [22]:
# 8.Text Wrap
import textwrap

def wrap(string, max_width):
    wrapper = textwrap.TextWrapper(max_width)
    word_list = wrapper.wrap(string)
    result = ""
    for word in word_list:
        result = result+ word + "\n"
    return result

if __name__ == '__main__':
    string, max_width = input(), int(input())
    result = wrap(string, max_width)
    print(result)

ABCDEFGHIJKLIMNOQRSTUVWXYZ
4
ABCD
EFGH
IJKL
IMNO
QRST
UVWX
YZ



In [23]:
# 9.Designer Door Mat
N, M = map(int, input().split())
for i in range(1, N, 2):
    print(((M - 3 * i) // 2) * '-' + (i * '.|.') + ((M - 3 * i) // 2) * '-')

print(((M - 7) // 2) * '-' + 'WELCOME' + ((M - 7) // 2) * '-')

for i in range(N - 2, -1, -2):
    print(((M - 3 * i) // 2) * '-' + (i * '.|.') + ((M - 3 * i) // 2) * '-')

5 15
------.|.------
---.|..|..|.---
----WELCOME----
---.|..|..|.---
------.|.------


In [25]:
# 10.String Formatting
def print_formatted(number):
    w = len(str(bin(number))[2:])
    for i in range(1,number+1):
        o = str(oct(i))[2:]
        h = str(hex(i))[2:]
        h = h.upper()
        b = str(bin(i))[2:]
        d = str(i)
    #used this site for printing in the asked format
    #https://www.kite.com/python/answers/how-to-print-a-string-at-a-fixed-width-in-python#:~:text=Use%20str.,aligns%20s%20to%20the%20right.&text=Use%20%22%7B0%3A_%3E5,with%20underscores%20instead%20of%20whitespace.
        print('{:>{width}} {:>{width}} {:>{width}} {:>{width}}'.format(d,o,h,b,width=w))
if __name__ == '__main__':
    n = int(input())
    print_formatted(n)

17
    1     1     1     1
    2     2     2    10
    3     3     3    11
    4     4     4   100
    5     5     5   101
    6     6     6   110
    7     7     7   111
    8    10     8  1000
    9    11     9  1001
   10    12     A  1010
   11    13     B  1011
   12    14     C  1100
   13    15     D  1101
   14    16     E  1110
   15    17     F  1111
   16    20    10 10000
   17    21    11 10001


In [27]:
# 11.Alphabet Rangoli

def print_rangoli(size):
    w = (size-1) * 2 + ((size * 2) - 1)
    for i in range(1,size):
        number_of_letter = (i*2) - 1
        s = ''
        letter_value = 97 + size - 1
        for i in range(0,number_of_letter):
            if(i != 0):
                s += '-' 
            s += chr(letter_value) 
            if(i<(number_of_letter-1) / 2):
                letter_value = letter_value - 1
            else:
                letter_value = letter_value + 1            
        print(s.center(w,'-'))
    
    for i in range(size,0,-1):
        number_of_letter = (i*2) - 1
        s = ''
        letter_value = 97 + size - 1
        for i in range(0,number_of_letter):
            if(i != 0):
                s += '-' 
            s += chr(letter_value) 
            if(i<(number_of_letter-1) / 2):
                letter_value = letter_value - 1
            else:
                letter_value = letter_value + 1            
        print(s.center(w,'-'))

if __name__ == '__main__':
    n = int(input())
    print_rangoli(n)


5
--------e--------
------e-d-e------
----e-d-c-d-e----
--e-d-c-b-c-d-e--
e-d-c-b-a-b-c-d-e
--e-d-c-b-c-d-e--
----e-d-c-d-e----
------e-d-e------
--------e--------


In [47]:
# 12.Capitalize!

import math
import os
import random
import re
import sys
def solve(s):
    s_new = s.split(' ')
    result = []
    for i in s_new:
        result.append(i.capitalize())
    return ' '.join(result)


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

    fptr.write(result + '\n')

    fptr.close()


Chris Alan


In [54]:
# 13. The Minion Game

def minion_game(string):
    kevin = 0
    stuart = 0
    vowels="AEIOU"
    for i in range(len(string)):
        if string[i] in vowels:
            kevin = kevin + len(string) - i
        else:
            stuart = stuart + len(string) - i    
    
    if kevin > stuart:
        print("Kevin",kevin)
    elif kevin == stuart:
        print("Draw")    
    else:
        print("Stuart",stuart)

if __name__ == '__main__':
    s = input()
    minion_game(s)

BANANA
Stuart 12


In [58]:
# 14.Merge the Tools!

def merge_the_tools(string, k):
    data = []
    for i in range(0, len(string), k):
        data.append(string[i : i + k])
    for sub in data:
        print("".join(dict.fromkeys(sub)))




if __name__ == '__main__':
    string, k = input(), int(input())
    merge_the_tools(string, k)

AABCAAADA
3
AB
CA
AD


## Part 4 : Sets

In [70]:
# 1.Introduction to Sets

def average(array):
    data = set(array)
    return round((sum(data)/len(data)), 3)

if __name__ == '__main__':
    n = int(input())
    arr = list(map(int, input().split()))
    result = average(arr)
    print(result)

10
161 182 161 154 176 170 167 171 170 174
169.375


In [88]:
# 2.No Idea!

from collections import Counter
n, m = map(int, input().split())
check_data = list(map(int,input().split()))
check_data1 = set(check_data)
check_data_counter = Counter(check_data)
A = set(map(int,input().split()))
B = set(map(int,input().split()))
intersect_a = list(check_data1 & A)
intersect_b = list(check_data1 & B)
result = 0
for element in intersect_a:
    result += check_data_counter[element]
for element in intersect_b:
    result -= check_data_counter[element]
print(result)

3 2
1 5 3
3 1
5 7
1


In [92]:
# 3.Symmetric Difference

n = int(input())
a = set(map(int,input().split()))
m = int(input())
b = set(map(int,input().split()))
ans = (a.difference(b)).union(b.difference(a))
ans = sorted(ans)
for item in ans:
    print(item)

4
2 4 5 9
4 
2 4 7 0
0
5
7
9


In [94]:
# 4.Set .add()

n = int(input())
country = set()
for i in range(n):
    country.add(input())
print(len(country))

4
a
a
b
c
3


In [95]:
# 5.Set .discard(), .remove() & .pop()
n = int(input())
numbers = set(map(int, input().split()))
n_cmnd = int(input())
for i in range(n_cmnd):
    cmnd = list(input().split())
    if cmnd[0] == 'pop':
        numbers.pop()
    elif cmnd[0] == 'discard':
        numbers.discard(int(cmnd[1]))
    elif cmnd[0] == 'remove':
        numbers.remove(int(cmnd[1]))
print(sum(numbers))

9
1 2 3 4 5 6 7 8 9
10
pop
remove 9
discard 9
discard 8
remove 7
pop
discard 6
remove 5
pop
discard 5
4


In [102]:
# 6.Set .union() Operation
a = int(input())
a_students = set(map(int, input().split()))
b = int(input())
b_students = set(map(int, input().split()))
ans = a_students.union(b_students)
print(len(ans))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
13


In [103]:
# 7.Set .intersection() Operation
a = int(input())
a_students = set(map(int, input().split()))
b = int(input())
b_students = set(map(int, input().split()))
ans = a_students.intersection(b_students)
print(len(ans))


9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
5


In [1]:
# 8.Set .difference() Operation
a = int(input())
a_students = set(map(int, input().split()))
b = int(input())
b_students = set(map(int, input().split()))
ans = a_students.difference(b_students)
print(len(ans))


9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
4


In [2]:
# 9.Set .symmetric_difference() Operation
a = int(input())
a_students = set(map(int, input().split()))
b = int(input())
b_students = set(map(int, input().split()))
ans = a_students.symmetric_difference(b_students)
print(len(ans))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
8


In [5]:
# 10.Set Mutations

a = int(input())
A = set(map(int, input().split()))
n = int(input())
for i in range(n):
    cmnd = list(input().split())
    new_set = set(map(int, input().split()))
    if cmnd[0] == 'intersection_update':
        A.intersection_update(new_set)
    elif cmnd[0] == 'update':
        A.update(new_set)
    elif cmnd[0] == 'symmetric_difference_update':
        A.symmetric_difference_update(new_set)
    elif cmnd[0] == 'difference_update':
        A.difference_update(new_set)
print(sum(A))

16
1 2 3 4 5 6 7 8 9 10 11 12 13 14 24 52
4
intersection_update 10
2 3 5 6 8 9 1 4 7 11
update 2
55 66
symmetric_difference_update 5
22 7 35 62 58
difference_update 7
11 22 35 55 58 62 66
38


In [4]:
# 11.The Captain's Room

k = int(input())
rooms = list(map(int, input().split()))
rooms_set = set(rooms)
rooms_sum = sum(rooms)
rooms_set_sum = sum(rooms_set) * k
for number in rooms_set:
    # all numbers repeated K times except captains room so if we calculate the difference, captains room must repeated k - 1 times
    if rooms_set_sum - rooms_sum == (k - 1) * number:
        print(number)
        break

5
1 2 3 6 5 4 4 2 5 3 6 1 6 5 3 2 4 1 2 5 1 4 3 6 8 4 3 1 5 6 2
8


In [11]:
# 12.Check Subset
n = int(input())
for i in range(n):
    a_number = int(input())
    a = set(map(int, input().split()))
    b_number = int(input())
    b = set(map(int, input().split()))
    if a.difference(b) == set():
        print(True)
    else:
        print(False)

3
5
1 2 3 5 6
9
9 8 5 6 3 2 1 4 7
True
1
2
5
3 6 5 4 1
False
7
1 2 3 5 6 8 9
3
9 8 2
False


In [12]:
# 13.Check Strict Superset
A = set(map(int, input().split()))
n = int(input())
ans = True
for i in range(n):
    other_set = set(map(int, input().split()))
    if A.difference(other_set) == set() or other_set.difference(A) != set():
        ans = False
        break
print(ans)    

1 2 3 4 5 6 7 8 9 10 11 12 23 45 84 78
2
1 2 3 4 5
100 11 12
False


## Part 5 : Collections

In [2]:
# 1.collections.Counter()

number_shoes = int(input())
size = list(map(int, input().split()))
costumers = int(input())
income = 0
for i in range(costumers):
    price = list(map(int, input().split()))
    if price[0] in size:
        income += int(price[1])
        size.remove(price[0])
print(income)
    



10
2 3 4 5 6 8 7 6 5 18
6
6 55
6 45
6 55
4 40
18 60
10 50
200


In [25]:
##### 2. DefaultDict Tutorial

from collections import defaultdict
n , m = map(int, input().split())
positions = defaultdict(list)
for i in range(n):
    A = input()
    positions[A].append(i + 1)
for i in range(m):
    B = input()
    if(positions[B] == []):
        print(-1)
    else:
        for pos in positions[B]:
            print(pos, end=" ")
        print()   
    



5 2
a
a
b
a
b
a
1 2 4 
b
3 5 


In [33]:
# 3.collections.namedtuple()

from collections import namedtuple
number = int(input())
labels = list(input().split())
marks = labels.index("MARKS")
sum_marks = 0
for i in range(number):
    data = list(input().split())
    sum_marks += float(data[marks])
print(sum_marks/number)
    


5
ID MARKS NAME CLASS
1 97 ray 7
2 50 stev 4
3 91 adr 9
4 72 stew 5
5 80 peter 6
78.0


In [37]:
# 4.Collections.OrderedDict()

import collections, re
number = int(input())
items = collections.OrderedDict()
for i in range(number):
    orders = re.split(r'(\d+)$',input().strip())
    name = orders[0]
    price = int(orders[1])
    if name not in items:
        items[name] = price
    else:
        items[name] = items[name] + price
            
for i in items:
    print(i + str(items[i]))


9
BANANA FRIES 12
POTATO CHIPS 30
APPLE JUICE 10
CANDY 5
APPLE JUICE 10
CANDY 5
CANDY 5
CANDY 5
POTATO CHIPS 30
BANANA FRIES 12
POTATO CHIPS 60
APPLE JUICE 20
CANDY 20


In [41]:
# 5.Word Order
import collections
n = int(input())
words = collections.OrderedDict()
for i in range(n):
    word = input()
    if word in words:
        words[word] += 1
    else:
        words[word] = 0

    
print(len(words))
for item in words:
    print(words[item]+1, end = " ")

4
bcdef
abcdefg
bcde
bcdef
3
2 1 1 

In [43]:
# 6.collections.deque()

from collections import deque
d = deque()
n = int(input())
for i in range(n):
    cmnd = list(input().split())
    if cmnd[0] == 'append':
        d.append(int(cmnd[1]))
    elif cmnd[0] == 'appendleft':
        d.appendleft(int(cmnd[1]))
    elif cmnd[0] == 'pop':
        d.pop()
    elif cmnd[0] == 'popleft':
        d.popleft()
for item in d:
    print(item , end = " ")

6
append 1
append 2
append 3
appendleft 4
pop
popleft
1 2 

In [50]:
# 7.Piling Up!
from collections import deque
number = int(input())
for t in range(number):
    size = int(input())
    dq = deque(map(int,input().split()))
    possible = True
    maximum = (2**31)+1

    while dq:

        left = dq[0]
        right = dq[-1]
        if left >= right and maximum >= left:
            maximum = dq.popleft()
        elif right >= left and maximum >= right:
            maximum = dq.pop()
        else:
            possible = False
            break
    if possible:
        print('Yes')
    else:
        print('No')   



1
3
427731488 922935208 973233245
Yes


In [81]:
# 8.Company Logo
from collections import Counter

data = sorted(input().strip())
data = Counter(data).most_common()
data = sorted(data,key = lambda x: (x[1] * -1,x[0]))
for i in range(3):
    print(data[i][0],data[i][1])


aabbbccde
b 3
a 2
c 2


## Part 6 : Date and Time

In [82]:
# 1.Calendar Module

import datetime
import calendar
m,d,y=map(int,input().split())
input_date = datetime.date(y,m,d)
print(calendar.day_name[input_date.weekday()].upper())

08 05 2015
WEDNESDAY


In [83]:
# 2.Time Delta
import math
import os
import random
import re
import sys
import datetime
def time_delta(t1, t2):
    time_format = "%a %d %b %Y %H:%M:%S %z"
    second1 = datetime.datetime.strptime(t1,time_format)
    second2 = datetime.datetime.strptime(t2,time_format)
    return str(int(abs((second1-second2).total_seconds())))
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        t1 = input()

        t2 = input()

        delta = time_delta(t1, t2)

        fptr.write(delta + '\n')

    fptr.close()


2
Sun 10 May 2015 13:54:36 -0700
Sun 10 May 2015 13:54:36 -0000
25200
Sat 02 May 2015 19:54:36 +0530
Fri 01 May 2015 13:54:36 -0000
88200


## Part 7 : Exceptions

In [89]:
# 1.Exceptions
n = int(input())
for i in range(n):
    m, n = input().split()
    try:
        print(int(m) // int(n))
    except Exception as e:
        print("Error Code:",e)


3
1 0
Error Code: integer division or modulo by zero
2 $
Error Code: invalid literal for int() with base 10: '$'
3 1
3


In [90]:
# 2.Incorrect Regex
# used this link https://stackoverflow.com/questions/19630994/how-to-check-if-a-string-is-a-valid-regex-in-python'''

import re
n = int(input())
for i in range(n):
    regex = input()
    try:
        re.compile(regex)
        print(True)
    except Exception as e:
        print(False)


2
.*\+
True
.*+
False


## Part 8 : Built-ins

In [15]:
# 1.Zipped!

students, subj = map(int, input().split())
data = [0 for i in range(students)]
for i in range(subj):
    scores = list(map(float, input().split()))
    for j in range(students):
        data[j] += scores[j]
for i in range(students):
    print(data[i] / subj)
    

    

5 3
89 90 78 93 80
90 91 85 88 86  
91 92 83 89 90.5
90.0
91.0
82.0
90.0
85.5


In [ ]:
# 2.Athlete Sort
import math
import os
import random
import re
import sys


if __name__ == '__main__':
    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])

    arr = []
    for arr_i in range(n):
       temp = [int(arr_temp) for arr_temp in input().strip().split(' ')]
       arr.append(temp)
    k = int(input().strip())
    
    sorted_arr = sorted(arr, key = lambda x : x[k])
    for row in sorted_arr:
        print(' '.join(str(y) for y in row))

In [16]:
# 3.ginortS
s = input()
s = sorted(s,key = lambda x:(x.isdigit() and int(x)%2==0, x.isdigit(),x.isupper(),x.islower(),x))
print(*(s),sep = '')



Sorting1234
ginortS1324


## Part 9 : Python Functionals

In [25]:
# 1.Map and Lambda Function
cube = lambda x:x**3 # complete the lambda function 

def fibonacci(n):
    # return a list of fibonacci numbers
    if n == 0:
        return []
    elif n == 1:
        return [0]
    else:
        fib = [0,1]
        for i in range(2,n):
            fib.append(fib[i-1]+fib[i-2])
        return fib

if __name__ == '__main__':
    n = int(input())
    print(list(map(cube, fibonacci(n))))

1
[0, 1]


## Part 10 : Regex and Parsing challenges

In [29]:
# 1.Detect Floating Point Number
import re
n = int(input())
for i in range(n):
    number = input()
    print(bool(re.search(r"^[-+]?\d*\.\d+$", number)))

1
0.5.0
False


In [30]:
# 2.Re.split()
regex_pattern = r"[.,]+"    # Do not delete 'r'.
import re
print("\n".join(re.split(regex_pattern, input())))

100,000,000.000
100
000
000
000


In [32]:
# 3.Group(), Groups() & Groupdict()
import re
data = input()
result = re.search(r'([A-Za-z0-9])\1', data)
if result == None:
    print(-1)
else:
    print(result.group(1))

..12345678910111213141516171820212223
1


In [35]:
# 4.Re.findall() & Re.finditer()
import re
data = input()
result = re.findall(r'(?<=[QWRTYPSDFGHJKLZXCVBNMqwrtypsdfghjklzxcvbnm])([AEIOUaeiou]{2,})(?=[QWRTYPSDFGHJKLZXCVBNMqwrtypsdfghjklzxcvbnm])',data)
if result:
    for i in result:
        print(i)
else:
    print(-1)


rabcdeefgyYhFjkIoomnpOeorteeeeet
ee
Ioo
Oeo
eeeee


In [36]:
# 5.Re.start() & Re.end()
import re
data = input()
substring = input()
flag = False
for i in range(len(data)):
    result = re.match(substring, data[i:])
    if result != None:
        print(( (i + result.start()) , (i + result.end() - 1)))
        flag = True
if flag == False:
    print('(-1, -1)')

aaadaa
aa
(0, 1)
(1, 2)
(4, 5)


In [38]:
# 6.Regex Substitution
import re
n = int(input())
for i in range(n):
    data = input()
    removed_and = re.sub(r'(?<= )(&&)(?= )',"and",data)
    removed_or = re.sub(r'(?<= )(\|\|)(?= )',"or",removed_and)
    print(removed_or,end='\n')

11
a = 1;
a = 1;
b = input();
b = input();
if a + b > 0 && a - b < 0:
if a + b > 0 and a - b < 0:
    start()
    start()
elif a*b > 10 || a/b < 1:
elif a*b > 10 or a/b < 1:
    stop()
    stop()
print set(list(a)) | set(list(b)) 
print set(list(a)) | set(list(b)) 
#Note do not change &&& or ||| or & or |
#Note do not change &&& or ||| or & or |
#Only change those '&&' which have space on both sides.
#Only change those '&&' which have space on both sides.
#Only change those '|| which have space on both sides.
#Only change those '|| which have space on both sides.
 
 


In [39]:
# 7.Validating Roman Numerals
regex_pattern = r"^M{0,3}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3})$"
	# Do not delete 'r'.

import re
print(str(bool(re.match(regex_pattern, input()))))

CDXXI
True


In [40]:
# 8.Validating phone numbers

import re
condition = re.compile(r'^[7-9]\d{9}$')
n = int(input())
for i in range(n):
    phone_number = input()
    if bool(re.match(condition, phone_number)):
        print("YES")
    else:
        print("NO")

2
9587456281
YES
1252478965
NO


In [43]:
# 9.Validating and Parsing Email Addresses
import email.utils, re
n = int(input())
for i in range(n):
    data = input()
    parsed = email.utils.parseaddr(data)[1].strip()
    ans = bool(re.match(r'(^[A-Za-z][A-Za-z0-9\._-]+)@([A-Za-z]+)\.([A-Za-z]{1,3})$',parsed))
    if ans == True:
        print(data)

2
DEXTER <dexter@hotmail.com>
DEXTER <dexter@hotmail.com>
VIRUS <virus!@variable.:p>


In [1]:
# 10.Hex Color Code

import re
n = int(input())
for i in range(n):
    data = input()
    ans = re.findall(r'(#[0-9A-Fa-f]{3}|#[0-9A-Fa-f]{6})(?:[;,.)]{1})',data)
    for i in ans:
        if i != '':
            print(i)

11
#BED
{
    color: #FfFdF8; background-color:#aef;
#FfFdF8
#aef
    font-size: 123px;
    background: -webkit-linear-gradient(top, #f9f9f9, #fff);
#f9f9f9
#fff
#Cab
{
    background-color: #ABC;
#ABC
    border: 2px dashed #fff;
#fff
}   



In [3]:
# 11.HTML Parser - Part 1

from html.parser import HTMLParser
class MyHTMLParser(HTMLParser):
    
    def handle_attr(self,attrs):
        for attr_val_tuple in attrs:
            print('->',attr_val_tuple[0],'>',attr_val_tuple[1])

    def handle_starttag(self,tag,attrs):
        print("Start :",tag)
        self.handle_attr(attrs)

    def handle_endtag(self,tag):
        print("End   :",tag)

    def handle_startendtag(self,tag, attrs):
        print("Empty :",tag)
        self.handle_attr(attrs)

parser = MyHTMLParser()
n = int(input())
data = ''
for i in range(n):
    data += input()
parser.feed(data)

2
<html><head><title>HTML Parser - I</title></head>
<body data-modal-target class='1'><h1>HackerRank</h1><br /></body></html>
Start : html
Start : head
Start : title
End   : title
End   : head
Start : body
-> data-modal-target > None
-> class > 1
Start : h1
End   : h1
Empty : br
End   : body
End   : html


In [5]:
# 12.HTML Parser - Part 2

from html.parser import HTMLParser
class MyHTMLParser(HTMLParser):
    def handle_comment(self, data):
        n_line = len(data.split('\n'))
        if n_line > 1:
            print('>>> Multi-line Comment')
        else:
            print('>>> Single-line Comment')
        if data.strip() == True:
            print(data)

    def handle_data(self, data):
        if data.strip():
            print(">>> Data")
            print(data)

n = int(input())
html = ""
for i in range(n):
    html += input().rstrip()
    html += '\n'
    
parser = MyHTMLParser()
parser.feed(html)
parser.close()

4
<!--[if IE 9]>IE9-specific content
<![endif]-->
<div> Welcome to HackerRank</div>
<!--[if IE 9]>IE9-specific content<![endif]-->
>>> Multi-line Comment
>>> Data
 Welcome to HackerRank
>>> Single-line Comment


In [6]:
# 13.Detect HTML Tags, Attributes and Attribute Values
from html.parser import HTMLParser
class CustomHTMLParser(HTMLParser):
    def handle_starttag(self,tag,attrs):
        print(tag)
        self.handle_attrs(attrs)
    def handle_startendtag(self,tag,attrs):
        print(tag)
        self.handle_attrs(attrs)
    def handle_attrs(self,attrs):
        for attrs_pair in attrs:
            print('->',attrs_pair[0].strip(),'>',attrs_pair[1].strip())        

n = int(input())
html_string = ''
for i in range(n):
    html_string += input()
    
customHTMLParser = CustomHTMLParser()
customHTMLParser.feed(html_string)
customHTMLParser.close()

9
<head>
<title>HTML</title>
</head>
<object type="application/x-flash" 
  data="your-file.swf" 
  width="0" height="0">
  <!-- <param name="movie" value="your-file.swf" /> -->
  <param name="quality" value="high"/>
</object>
head
title
object
-> type > application/x-flash
-> data > your-file.swf
-> width > 0
-> height > 0
param
-> name > quality
-> value > high


In [7]:
# 14.Validating UID
import re
upper = r'.*([A-Z].*){2,}'
digit = r'.*([0-9].*){3,}'
alphanum = r'([A-Za-z0-9]){10}$'
n = int(input())
repeat = r'.*(.).*\1'
for i in range(n):
    uid = input().strip()
    upper_res = bool(re.match(upper,uid))
    digit_res = bool(re.match(digit,uid))
    alphanum_res = bool(re.match(alphanum,uid))
    repeat_res = bool(re.match(repeat,uid))    
    if upper_res and digit_res and alphanum_res and not repeat_res:
        print('Valid')
    else:
        print('Invalid')

2
B1CD102354
Invalid
B1CDEF2354
Valid


In [9]:
# 15.Validating Credit Card Numbers
from re import match, findall
n = int(input())
for i in range(n):
    number = input().strip()
    number2 = number.replace('-','')
    valid = True
    length_16 = bool(match(r'^[4-6]\d{15}$',number))
    length_19 = bool(match(r'^[4-6]\d{3}-\d{4}-\d{4}-\d{4}$',number))    
    consecutive = bool(findall(r'(?=(\d)\1\1\1)',number2))
    if length_16 == True or length_19 == True:
        if consecutive == True:
            valid=False
    else:
        valid = False       
    if valid == True:
        print('Valid')
    else:
        print('Invalid')

6
4123456789123456
Valid
5123-4567-8912-3456
Valid
61234-567-8912-3456
Invalid
4123356789123456
Valid
5133-3367-8912-3456
Invalid
5123 - 3567 - 8912 - 3456
Invalid


In [10]:
# 16.Validating Postal Codes

regex_integer_in_range = r"^[1-9][0-9]{5}$"	# Do not delete 'r'.
regex_alternating_repetitive_digit_pair = r"(?=([0-9])[0-9]\1)"	# Do not delete 'r'.

import re
P = input()

print (bool(re.match(regex_integer_in_range, P)) 
and len(re.findall(regex_alternating_repetitive_digit_pair, P)) < 2)


110000
False


In [11]:
# 17. Matrix Script
import math
import os
import random
import re
import sys

first_multiple_input = input().rstrip().split()

n = int(first_multiple_input[0])

m = int(first_multiple_input[1])

matrix = [''] * (n*m)

for i in range(n):
    line = input()
    for j in range(m):
       matrix[i + (j * n)] = line[j]
ans = ''.join(matrix)
ans = re.sub(r'(?<=[A-Za-z0-9])([ !@#$%&]+)(?=[A-Za-z0-9])',' ',ans)
print(ans)

7 3
Tsi
h%x
i #
sM 
$a 
#t%
ir!
This is Matrix#  %!


## Part 11 : XML

In [ ]:
# 1.XML 1 - Find the Score

import sys
import xml.etree.ElementTree as etree


def get_attr_number(node):
    count = 0
    for tag in node:
        count += get_attr_number(tag)
    return count + len(node.attrib)
if __name__ == '__main__':
    sys.stdin.readline()
    xml = sys.stdin.read()
    tree = etree.ElementTree(etree.fromstring(xml))
    root = tree.getroot()
    print(get_attr_number(root))

In [21]:
# 2.XML2 - Find the Maximum Depth
import xml.etree.ElementTree as etree

maxdepth = 0
def depth(elem, level):
    global maxdepth
    if (level == maxdepth):
        maxdepth += 1
    for item in elem:
        depth(item, level + 1)

if __name__ == '__main__':
    n = int(input())
    xml = ""
    for i in range(n):
        xml =  xml + input() + "\n"
    tree = etree.ElementTree(etree.fromstring(xml))
    depth(tree.getroot(), -1)
    print(maxdepth)


6
<feed xml:lang='en'>
    <title>HackerRank</title>
    <subtitle lang='en'>Programming challenges</subtitle>
    <link rel='alternate' type='text/html' href='http://hackerrank.com/'/>
    <updated>2013-12-25T12:00:00</updated>
</feed>
1


## Part 12 : Closures and Decorations

In [18]:
# 1.Standardize Mobile Number Using Decorators
def wrapper(f):
    def fun(l):
        # complete the function
        f(['+91 ' + c[-10:-5] + ' ' + c[-5:] for c in l])
    return fun

@wrapper
def sort_phone(l):
    print(*sorted(l), sep='\n')

if __name__ == '__main__':
    l = [input() for _ in range(int(input()))]
    sort_phone(l) 


In [23]:
# 2.Decorators 2 - Name Directory

import operator

def person_lister(f):
    def inner(people):
        # complete the function
        return map(f, sorted(people, key=lambda x: int(x[2])))

    return inner

@person_lister
def name_format(person):
    return ("Mr. " if person[3] == "M" else "Ms. ") + person[0] + " " + person[1]

if __name__ == '__main__':
    people = [input().split() for i in range(int(input()))]
    print(*name_format(people), sep='\n')

3
Mike Thomson 20 M
Robert Bustle 32 M
Andria Bustle 30 F
Mr. Mike Thomson
Ms. Andria Bustle
Mr. Robert Bustle


## Part 13 : Numpy

In [24]:
# 1.Shape and Reshape

import numpy as np
matrix = np.array(input().split(), dtype = "i4")
print(matrix.reshape(3,3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
# 2.Transpose and Flatten

import numpy as np
n, m = map(int, input().split())
data = np.ones(shape = (n,m), dtype = "i4")
for i in range(0,n):
    data[i] = list(input().split())
print(data.transpose())
print(data.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [26]:
# 3.Concatenate

import numpy as np
n, m, p = map(int, input().split())
first = np.zeros(shape = (n,p), dtype = "i")
second = np.zeros(shape = (m,p), dtype = "i")
for i in range(0,n):
    first[i] = list(input().split())
for i in range(0,m):
    second[i] = list(input().split())
print(np.concatenate((first, second), axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [46]:
# 4.Arrays
import numpy as np

def arrays(arr):
    # complete this function
    # use numpy.array
    return np.array(arr[::-1], float)

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [51]:
# 5.zeros and Ones

import numpy as np
size = tuple(map(int, input().split()))
print(np.zeros(size, dtype = np.int))
print(np.ones(size, dtype = np.int))

3 2
[[0 0]
 [0 0]
 [0 0]]
[[1 1]
 [1 1]
 [1 1]]


C:\Users\mehdi\AppData\Local\Temp/ipykernel_15512/1430767518.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(np.zeros(size, dtype = np.int))
C:\Users\mehdi\AppData\Local\Temp/ipykernel_15512/1430767518.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release no

In [54]:
# 6.Eye and Identity
import numpy as np
np.set_printoptions(legacy = '1.13')
N, M = map(int, input().split())
print(np.eye(N,M))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [69]:
# 7.Array Mathematics

import numpy as np
n, m = map(int, input().split())
arr_a = []
arr_b = []

for i in range(n):
    a = list(map(int, input().split()))
    arr_a.append(a)
for i in range(n):
    b = list(map(int, input().split()))
    arr_b.append(b)
arr_a = np.array(arr_a)
arr_b = np.array(arr_b)
print(arr_a + arr_b)
print(arr_a - arr_b)
print(arr_a * arr_b)
print(arr_a // arr_b)
print(arr_a % arr_b)
print(arr_a ** arr_b)


1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [77]:
# 8.Floor, Ceil and Rint
import numpy as np
np.set_printoptions(legacy='1.13')

data = np.array(input().split(), float)
print(np.floor(data))
print(np.ceil(data))
print(np.rint(data))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [82]:
# 9.Sum and Prod
import numpy as np
n, m = map(int,input().split())
data = []
for i in range(n):
    temp = list(map(int, input().split()))
    data.append(temp)
data = np.array(data)
print(np.prod((np.sum(data, axis = 0))))

2 2
1 2
3 4
24


In [83]:
# 10.Min and Max
import numpy as np
n, m = map(int,input().split())
data = []
for i in range(n):
    temp = list(map(int, input().split()))
    data.append(temp)
data = np.array(data)
print(np.max((np.min(data, axis = 1))))

4 2
2 5
3 7
1 3
4 0
3


In [95]:
# 11.Mean, Var, and Std
import numpy as np
n, m = map(int,input().split())
data = []
for i in range(n):
    temp = list(map(int, input().split()))
    data.append(temp)
data = np.array(data)
print(np.mean(data, axis = 1))
print(np.var(data, axis = 0))
print(round(np.std(data), 11))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [99]:
# 12.Dot and Cross
import numpy as np
n = int(input())
A = []
for i in range(n):
    temp = list(map(int, input().split()))
    A.append(temp)
B = []
for i in range(n):
    temp = list(map(int, input().split()))
    B.append(temp)

print(np.matmul(A,B))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [101]:
# 13.Inner and outer
import numpy as np
A = np.array(input().split(), int)
B = np.array(input().split(), int)
print(np.inner(A,B))
print(np.outer(A,B))


0 1
2 3
3
[[0 0]
 [2 3]]


In [102]:
# 14.Polynomials
import numpy as np
coef = list(map(float, input().split()))
point = float(input())
print(np.polyval(coef, point))

1.1 2 3
0
3.0


In [104]:
# 15.Linear Algebra
import numpy as np
n = int(input())
a = []
for i in range(n):
    temp = list(map(float, input().split()))
    a. append(temp)
print(np.linalg.det(a))


2
1.1 1.1
1.1 1.2
0.11


# Problem 2

In [107]:
# 1.Birthday Cake Candles

import math
import os
import random
import re
import sys

#
# Complete the 'birthdayCakeCandles' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY candles as parameter.
#

def birthdayCakeCandles(candles):
    max_size = max(candles)
    counter = 0
    for candle in candles:
        if candle == max_size:
            counter += 1
    return counter
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    candles_count = int(input().strip())

    candles = list(map(int, input().rstrip().split()))

    result = birthdayCakeCandles(candles)

    fptr.write(str(result) + '\n')

    fptr.close()


In [ ]:
# 2. Number Line Jumps

import math
import os
import random
import re
import sys

#
# Complete the 'kangaroo' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. INTEGER x1
#  2. INTEGER v1
#  3. INTEGER x2
#  4. INTEGER v2
#

def kangaroo(x1, v1, x2, v2):
    # Write your code here
    for n in range(10000):
        if(x1 + v1 == x2 + v2):
            return "YES"
        x1 += v1
        x2 += v2
    return "NO"
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    x1 = int(first_multiple_input[0])

    v1 = int(first_multiple_input[1])

    x2 = int(first_multiple_input[2])

    v2 = int(first_multiple_input[3])

    result = kangaroo(x1, v1, x2, v2)

    fptr.write(result + '\n')

    fptr.close()



In [ ]:
# 3.Viral Advertising

import math
import os
import random
import re
import sys

# Complete the viralAdvertising function below.
def viralAdvertising(n):
    shared = 5
    ans = 0
    for i in range(1, n + 1):
        liked = shared // 2
        ans += liked
        shared = liked * 3
    return ans

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    result = viralAdvertising(n)

    fptr.write(str(result) + '\n')

    fptr.close()

In [ ]:
# 4.Recursive Digit Sum
import math
import os
import random
import re
import sys

#
# Complete the 'superDigit' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. STRING n
#  2. INTEGER k
#

def superDigit(n):
    if len(n) == 1:
        return int(n)
    else:
        temp = str(sum([int(x) for x in n]))
        return superDigit(temp)
def digitSum(number, k):
    temp = str(k*sum([int(x) for x in number]))
    return superDigit(temp)        
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = first_multiple_input[0]

    k = int(first_multiple_input[1])

    result = digitSum(n, k)

    fptr.write(str(result) + '\n')

    fptr.close()

In [ ]:
# 5.Insertion Sort - Part 1

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    # Write your code here
    probe = arr[-1]
    
    for ind in range(len(arr)-2, -1, -1):
        if arr[ind] > probe:
            arr[ind+1] = arr[ind]
            print(" ".join(map(str, arr)))
        else:
            arr[ind+1] = probe
            print(" ".join(map(str, arr)))
            break
    if arr[0] > probe:
        arr[0] = probe
        print(" ".join(map(str, arr)))

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)


In [ ]:
# 6.Insertion Sort - Part 2


import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort2' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#
def insertionSort1(start, arr):
    probe = arr[start]
    
    for ind in range(start-1, -1, -1):
        if arr[ind] > probe:
            arr[ind+1] = arr[ind]
        else:
            arr[ind+1] = probe
            break
    if arr[0] > probe:
        arr[0] = probe

def insertionSort2(n, arr):
    for ind in range(1, len(arr)):
        insertionSort1(ind, arr)
        print(" ".join(map(str, arr)))

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort2(n, arr)



### All 98 problems solved and submitted to the hackkerrank.